import Head from "next/head";

function Home() {
  return (
    <div className="bg-white dark:bg-black">
      <Head>
        <title>app_title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="p-20 bg-black text-white">
        <h1 className="text-3xl text-center">Next.js Boilerplate</h1>
      </header>
      <main className="container min-h-screen flex items-center justify-center flex-col"></main>
      <footer>
        <p>footer here</p>
      </footer>
    </div>
  );
}

export default Home;
